import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../../app/router/routes.dart';
import '../../../../l10n/gen/app_localizations.dart';
import '../entities/care_compass_item.dart';

class CareCompassPage extends StatelessWidget { const CareCompassPage({super.key}); @override Widget build(BuildContext c){final l=AppLocalizations.of(c);final items=[CareCompassItem(id:'prep',title:l.compassPrepareTitle,subtitle:l.compassPrepareSubtitle,kind:CompassItemKind.preparation,status:CompassItemStatus.now,dueAt:DateTime.now(),route:'/care/readiness/demo',accent:0xffD99B54),CareCompassItem(id:'visit',title:l.compassVisitTitle,subtitle:l.compassVisitSubtitle,kind:CompassItemKind.appointment,status:CompassItemStatus.next,dueAt:DateTime.now(),route:Routes.appointments,accent:0xff4C8DCE),CareCompassItem(id:'meds',title:l.compassMedicationTitle,subtitle:l.compassMedicationSubtitle,kind:CompassItemKind.medication,status:CompassItemStatus.waiting,dueAt:DateTime.now(),route:Routes.medications,accent:0xff6C63A8)];return Scaffold(appBar:AppBar(title:Text(l.compassTitle),actions:[IconButton(onPressed:()=>c.push(Routes.familyCare),icon:const Icon(Icons.people_alt_outlined),tooltip:l.familyCareTitle)]),body:CustomScrollView(slivers:[SliverToBoxAdapter(child:_CompassHero(l:l)),SliverPadding(padding:const EdgeInsetsDirectional.fromSTEB(20,8,20,24),sliver:SliverList(delegate:SliverChildListDelegate([Text(l.compassTodayTitle,style:Theme.of(c).textTheme.titleLarge),const SizedBox(height:10),...items.map((x)=>_CompassCard(item:x))])))]));}}
class _CompassHero extends StatelessWidget { const _CompassHero({required this.l}); final AppLocalizations l; @override Widget build(BuildContext c)=>Padding(padding:const EdgeInsetsDirectional.fromSTEB(20,20,20,24),child:Container(padding:const EdgeInsets.all(24),decoration:BoxDecoration(borderRadius:BorderRadius.circular(32),gradient:const LinearGradient(begin:AlignmentDirectional.topStart,end:AlignmentDirectional.bottomEnd,colors:[Color(0xff163B5C),Color(0xff0B6E69),Color(0xff3C9D8D]))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:Colors.white24,borderRadius:BorderRadius.circular(16)),child:const Icon(Icons.explore_outlined,color:Colors.white,size:28)),const Spacer(),Text(l.compassCalmScore,style:const TextStyle(color:Colors.white70))]),const SizedBox(height:26),Text(l.compassGreeting,style:Theme.of(c).textTheme.headlineMedium?.copyWith(color:Colors.white,fontWeight:FontWeight.w800)),const SizedBox(height:8),Text(l.compassHeroSubtitle,style:Theme.of(c).textTheme.bodyLarge?.copyWith(color:Colors.white70)),const SizedBox(height:22),Row(children:[_Metric(value:'72%',label:l.compassProgress),const SizedBox(width:24),_Metric(value:'3',label:l.compassOpenLoops)])]));}
class _Metric extends StatelessWidget { const _Metric({required this.value,required this.label}); final String value,label; @override Widget build(BuildContext c)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(value,style:const TextStyle(color:Colors.white,fontSize:24,fontWeight:FontWeight.w800)),Text(label,style:const TextStyle(color:Colors.white70))]);}
class _CompassCard extends StatelessWidget { const _CompassCard({required this.item}); final CareCompassItem item; @override Widget build(BuildContext c)=>Card(child:InkWell(onTap:()=>c.push(item.route),borderRadius:BorderRadius.circular(18),child:Padding(padding:const EdgeInsets.all(18),child:Row(children:[Container(width:12,height:56,decoration:BoxDecoration(color:Color(item.accent),borderRadius:BorderRadius.circular(8))),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(item.title,style:Theme.of(c).textTheme.titleMedium),const SizedBox(height:4),Text(item.subtitle,style:Theme.of(c).textTheme.bodyMedium)])),const Icon(Icons.arrow_forward_ios_rounded,size:16)]))));}
