import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/di/injector.dart';
import '../../../../core/theme/theme_controller.dart';
import '../../../../core/theme/theme_preference.dart';
import '../../../../l10n/gen/app_localizations.dart';

class SettingsPage extends StatefulWidget { const SettingsPage({super.key}); @override State<SettingsPage> createState()=>_SettingsPageState(); }
class _SettingsPageState extends State<SettingsPage>{ late final ThemeController theme; @override void initState(){super.initState();theme=getIt<ThemeController>();} @override Widget build(BuildContext c){final l=AppLocalizations.of(c);return AnimatedBuilder(animation:theme,builder:(context,_){return Scaffold(appBar:AppBar(title:Text(l.settingsTitle)),body:ListView(children:[_section(context,l.settingsAccountSection,[ListTile(title:Text(l.settingsAccountSection),leading:const Icon(Icons.person_outline),onTap:()=>context.push('/settings/profile'))]),_section(context,l.settingsAppearanceSection,[ListTile(title:Text(l.settingsThemeSystem),leading:const Icon(Icons.brightness_6_outlined),onTap:()=>theme.setTheme(ThemePreference.system)),ListTile(title:Text(l.settingsThemeLight),onTap:()=>theme.setTheme(ThemePreference.light)),ListTile(title:Text(l.settingsThemeDark),onTap:()=>theme.setTheme(ThemePreference.dark)),ListTile(title:Text(l.settingsTextSizeCompact),onTap:()=>theme.setTextScale(.9)),ListTile(title:Text(l.settingsTextSizeDefault),onTap:()=>theme.setTextScale(1)),ListTile(title:Text(l.settingsTextSizeLarge),onTap:()=>theme.setTextScale(1.15)),SwitchListTile(title:Text(l.settingsReduceMotion),value:theme.reduceMotion,onChanged:theme.setReduceMotion)]),_section(context,l.settingsPrivacySection,[ListTile(title:Text(l.settingsBiometricUnlock),leading:const Icon(Icons.fingerprint),onTap:()=>context.push('/settings/privacy')),ListTile(title:Text(l.settingsActiveSessions),onTap:()=>context.push('/settings/sessions'))]),_section(context,l.settingsDataSection,[ListTile(title:Text(l.settingsClearCache),onTap:()=>context.push('/settings/data')),ListTile(title:Text(l.settingsExportData),onTap:()=>context.push('/settings/data'))]),_section(context,l.settingsAboutSection,[ListTile(title:Text(l.settingsAboutSection),onTap:()=>context.push('/settings/about'))]) ]);});} Widget _section(BuildContext c,String title,List<Widget> children)=>Padding(padding:const EdgeInsetsDirectional.only(bottom:8),child:Card(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Padding(padding:const EdgeInsetsDirectional.fromSTEB(16,16,16,8),child:Text(title,style:Theme.of(c).textTheme.titleMedium)),...children])));}
