import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Initializes Firebase using the native platform configuration generated by
/// `flutterfire configure`.
///
/// Android and iOS use their native Firebase configuration files. Web requires
/// the generated FlutterFire options because it has no native Firebase config.
Future<void> initializeFirebase() async {
  if (kIsWeb) {
    throw StateError(
      'Firebase web configuration is missing. Run "flutterfire configure" '
      'to generate firebase_options.dart and initialize Firebase for web.',
    );
  }

  await Firebase.initializeApp();
}
